name: DAuth

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install
      
      - name: Build project
        run: yarn run build
      
      - name: Set up Git user
        run: |
          git config --global user.name Team-B1ND
          git config --global user.email mdev_team@dgsw.hs.kr

      - name: Build and deploy
        env:
          GIT_USER: Team-B1ND
          GIT_EMAIL: mdev_team@dgsw.hs.kr
        run: yarn run deploy
        